
version: '3.8'

services:
  inventory-api:
    build:
      context: ./src/InventoryService/1-Presentation/EcommerceFlow.InventoryService.API
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  sales-api:
    build:
      context: ./src/SalesService/1-Presentation/EcommerceFlow.SalesService.API
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  gateway-api:
    build:
      context: ./src/ApiGateway/EcommerceFlow.ApiGateway
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
